config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do 
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end
  root to: 'posts#index'
  resources :posts do
    resources :comments, except: [:index, :show]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { in: 1..100 }
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :user_id, presence: true
    validates :content, presence: true, length: { in: 1..100 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password)}
         end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :current_post
  before_action :current_comment, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_user, only: [:new, :create]

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.create(comment_params)
    puts @comment.post_id
    redirect_to post_path(@post)
  end
  
  def edit
  end

  def update
    @comment.update(comment_params)

    redirect_to post_path(@post)
  end

  def destroy
    puts "destroy Comment"
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit( :content, :user_id)
  end

  def current_post
    @post = Post.find(params[:post_id])
    user = User.find(@post.user_id)
    @post_author_name = user.first_name + " " + user.last_name
  end

  def current_comment
    @comment = @post.comments.find(params[:id])
    user = User.find(@comment.user_id)
    @comment_author_name = user.first_name + " " + user.last_name
  end

  def set_user
    @user = User.find(current_user.id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :current_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_user, only: [:new, :create]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
    @posts.each do |post|
      user = User.find(post.user_id)
      post.author = user.first_name + " " + user.last_name
    end
  end

  def show
  end

  def new
    @post = @user.posts.build
  end

  def create
    post = @user.posts.create(post_params)
    redirect_to posts_path
  end
  
  def edit
  end

  def update
    @post.update(post_params)

    redirect_to post_path(@post)
  end

  def destroy
    puts "IN DELETEEEE"
    @post.destroy

    redirect_to posts_path
  end


  private

  def post_params
    params.require(:post).permit(:content, :user_id)
  end

  def current_post
    @post = Post.find(params[:id])
    user = User.find(@post.user_id)
    @post_author_name = user.first_name + " " + user.last_name;
  end

  def set_user
    @user = User.find(current_user.id)
  end

  def authorize_user
    if current_user.id != @post.user_id
      redirect_to post_path(@post), notice: "Not Authorized User!"
    end
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
    
  <% user = User.find(comment.user_id) %>
  <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1"> <%=  user.first_name + " " + user.last_name %> </h5>
  </div>
  <p class=""> <%= comment.content %> </p>
    <% if user_signed_in? and comment.user_id == current_user.id %>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <%= link_to "Edit", edit_post_comment_path(comment.post_id,comment), class: 'btn btn-light' %> 
            <%= button_to "Delete",[comment.post, comment], method: :delete, class: 'btn btn-light' %>
        </div>
    <% end %>


</div>

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/comments/edit.html.erb
<h3>Update Comment</h3>



<%= render @post %>
<div class="container mt-3">
<div class = "m-2">
<h3> New Comment </h3>
</div>
<%= form_with model: [@post, @comment] do |f| %>
<div class="card">
  <div class="card-body">

    <div class="mb-3">
      <h5><%= @comment_author_name %></h5>
    </div>

    <div class="mb-3">
      <%= f.text_area :content, { class: "form-control", placeholder: "Leave your comment.." } %>
    </div>

   
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
     <%= link_to "Back", post_path(@post), class: "btn btn-link"%>
     <%= f.submit "Submit", class: "btn btn-dark" %>
    </div>
    

  </div>
</div>
<% end %>
</div>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<%= render @post %>
<div class="container mt-3">
<div class = "m-2">
<h3> New Comment </h3>
</div>
<%= form_with(model: [@post, @post.comments.build]) do |f| %>
<div class="card">
  <div class="card-body">

    <div class="mb-3">
      <h5><%= current_user.first_name + " " + current_user.last_name %></h5>
    </div>

    <div class="mb-3">
      <%= f.text_area :content, { class: "form-control", placeholder: "Leave your comment.." } %>
    </div>

   
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
     <%= link_to "Back", post_path(@post), class: "btn btn-link"%>
     <%= f.submit "Submit", class: "btn btn-dark" %>
    </div>

    <%= f.number_field :user_id, { class: "form-control", value: current_user.id, id: :comment_user_id, type: :hidden } %>
    

  </div>
</div>
<% end %>
</div>

app/views/layouts/_alert.html.erb
 <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #563d7c;">
  <a class="navbar-brand" href="#"><%= link_to "Blog", posts_path, class:"navbar-brand"%> </a>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      
      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Posts", posts_path, class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "New Post", new_post_path, class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path,method: :delete, class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
        </li>
      <% end %>

     

     
      
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>

    <%= render "/layouts/header" %>
    <%= render "/layouts/alert" %>
    

   

    
    <div class="container">
    <%= yield %>
     </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
 

 <div class="card border-dark mt-3">
    <div class="card-body">
      <h5 class="card-title"> <%= @post_author_name %> </h5>
      <p class="card-text"> <%= post.content %> </p>
     
     <% if user_signed_in? && @post.user_id == current_user.id %>
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
         <%= link_to "Edit", edit_post_path(@post), class: 'btn btn-outline-dark' %> 
         <%= button_to "Delete", @post, method: :delete, class: 'btn btn-outline-dark' %>
      </div>
      <% end %>
     
    </div>
  </div>

  
</div>

app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

app/views/posts/edit.html.erb
<div class="container m-4">
<h3>Update Post Details</h3>
<%= form_with(model: @post) do |f| %>
<div class="card border-dark">
  <div class="card-body">

    <div class="mb-3">
      <h5><%= @post_author_name %></h5>
    </div>

    <div class="mb-3">
      <%= f.text_area :content, { class: "form-control", placeholder: "content" } %>
    </div>

   
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
     <%= link_to "Back to Post", post_path(@post), class: "btn btn-link"%>
     <%= f.submit "Submit", class: "btn btn-dark" %>
    </div>
    

  </div>
</div>
<% end %>
</div>

app/views/posts/index.html.erb
<div class="container m-4">

<h1>Posts</h1>
<div class = "container m-2" >
<div class="list-group" id="posts">
 
  <% @posts.each do |post| %>
    <div class="card mt-2 border-dark">
    <div class="card-body">
      <h5 class="card-title"> <%= post.author %> </h5>
      <p class="card-text"> <%= post.content %> </p>
    
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      <%= link_to "view", post, class: "btn btn-outline-dark"  %> 
    </div>
    </div>
  </div>
  <% end %>

  <div class="d-grid gap-2 col-4 mx-auto m-2">
   <%= link_to "New Post", new_post_path , class: "btn btn-dark mx-auto"  %> 
   </div>

</div>

</div>

app/views/posts/new.html.erb
<div class="container m-4">
<%= form_with(model: @post) do |f| %>
<div class="card">
  <div class="card-body">

    
    <div class="mb-3">
      <h5><%= @user.first_name + " " + @user.last_name %></h5>
    </div> 

    <div class="mb-3">
      <%= f.text_area :content, { class: "form-control", placeholder: "What is in your mind?" } %>
    </div>

   
    <%= f.number_field :user_id, { class: "form-control", value: current_user.id, id: :post_user_id, type: :hidden } %>
  

   
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
     <%= link_to "Back to Posts", posts_path, class: "btn btn-link"%>
     <%= f.submit "Submit", class: "btn btn-dark" %>
    </div>
    

  </div>
</div>
<% end %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<div class="container mt-3">
<div>
 <div class = "m-2">
  <h3> Comments: </h3>
 </div>

  <div class="list-group">
    <% @post.comments.each do |comment| %>
     <li class="list-group-item">
      <%= render comment %>
      </li>
    <% end %>
  </div>

  <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-3">
         <%= link_to "Back to Posts", posts_path, class: 'btn btn-link' %> 
          <%= link_to "New Comment", new_post_comment_path(@post), class: 'btn btn-dark' %> 
       
    </div>

</div>

</div>